<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Fcg.Core.Abstractions.Application</PackageId>
    <Version>1.0.0</Version>
    <Authors>Alex Oliveira Ferreira</Authors>
    <Company>FiapCloudGames</Company>
    <RepositoryUrl>https://github.com/alexoliveiraferreiradev/fcg.core.abstractions</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Description>Pacote principal contendo as abstrações da application (Validation Behavior) compartilhadas entre os microsserviços do Fiap Cloud Games.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fcg.Core.WebApi\Fcg.Core.WebApi.csproj" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
